<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $classes = [
            ['grade' => '6', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '6', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '6', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '6', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '6', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => '6', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'B03', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'B10', 'tuition_group_ids' => ''],
            ['grade' => '7', 'name' => 'B30', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'B', 'tuition_group_ids' => ''],
            ['grade' => '8', 'name' => 'B30', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '9', 'name' => 'B', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A06', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'B', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'B30', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E01', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E02', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E03', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E04', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E05', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E06', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E07', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E08', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E09', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E10', 'tuition_group_ids' => ''],
            ['grade' => '10', 'name' => 'E35', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A06', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A07', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A30', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B01', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B02', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B03', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B04', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B05', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B06', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B07', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B08', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B09', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B10', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B11', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B12', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B13', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B14', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B15', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B16', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B17', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B18', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B19', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B20', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B21', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'B30', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E01', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E02', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E03', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E04', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E05', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E06', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E07', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E08', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E09', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E30', 'tuition_group_ids' => ''],
            ['grade' => '11', 'name' => 'E35', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A30', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'A35', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B01', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B02', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B03', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B04', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B05', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B06', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B30', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'B35', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E01', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E02', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E03', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E04', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E05', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E06', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E07', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E08', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E09', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E10', 'tuition_group_ids' => ''],
            ['grade' => '12', 'name' => 'E35', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A01', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A02', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A03', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A04', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A05', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A06', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'A30', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B01', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B02', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B03', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B04', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B05', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B06', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'B30', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E01', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E02', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E03', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E04', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E05', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E06', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E07', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E08', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E09', 'tuition_group_ids' => ''],
            ['grade' => 'LT', 'name' => 'E30', 'tuition_group_ids' => '']
        ];

        DB::table('classes')->insert($classes);
    }
}
